from setuptools import setup, find_packages

setup(
    name="e-commerce-be",
    version="0.1.0",
    description="Backend API for E-Commerce Platform with Admin Dashboard",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    install_requires=[
        "fastapi==0.109.0",
        "uvicorn==0.27.0",
        "sqlalchemy==2.0.25",
        "pydantic==2.6.0",
        "pydantic-settings==2.1.0",
        "python-jose[cryptography]==3.3.0",
        "passlib[bcrypt]==1.7.4",
        "python-multipart==0.0.6",
        "alembic==1.13.1",
        "psycopg2-binary==2.9.9",
        "python-dotenv==1.0.0",
        "supabase==2.3.0",
        "httpx==0.26.0",
        "email-validator==2.1.0.post1",
        "python-slugify==8.0.4",
        "Pillow==10.2.0",
        "aiofiles==23.2.1",
        "redis==5.0.1",
        "tenacity==8.2.3",
    ],
    python_requires=">=3.12",
) 